name: "Push on any branch"


on:
    push:
        branches:
            - '**'

jobs:
    push_on_anybranch:
        runs-on: ubuntu-latest
        steps:
            - name: "Triger on any branch"
              run: echo " new push detected"

            - name: "Push time "
              run: date

            - name: "Trigger on any branch"
              run: echo "New push detected on branch: ${{ github.ref_name }}"